# Screen
WINDOW_HEIGHT = 640
WINDOW_WIDTH = 640
WINDOW_SIZE = (WINDOW_WIDTH, WINDOW_HEIGHT)
WINDOW_MIDPOINT = (WINDOW_WIDTH // 2, WINDOW_HEIGHT // 2)
assert WINDOW_WIDTH * WINDOW_HEIGHT % 2 == 0, 'Screen must have an even height and width'
START_GAME_BUTTON_RECT = [130, 435, 385, 120]
START_GAME_BUTTON_RECT_CENTRE = (130 + 385/2, 435 + 120/2)

running = True


# Colours: RGB
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
LIME = (0, 255, 0)
BLUE = (0, 0, 255)
YELLOW = (255, 255, 0)
CYAN = (0, 255, 255)
MAGENTA = (255, 0, 255)
SILVER = (192, 192, 192)
GRAY = (128, 128, 128)
MAROON = (128, 0, 0)
OLIVE = (128, 128, 0)
GREEN = (0, 128, 0)
PURPLE = (128, 0, 128)
TEAL = (0, 128, 128)
NAVY = (0, 0, 128)

ALL_SQUARE_COLOURS = [RED, GREEN, BLUE, PURPLE]

colours_dict = {
    RED: "RED",
    GREEN: "GREEN",
    BLUE: "BLUE",
    PURPLE: "PURPLE",
}

# Fonts:
COMICSANS_MS = 'comicsansms'
CONSOLAS = 'consolas'
ARIAL = 'arial'
CALIBRI = 'calibri'

# Squares
SQUARE_LENGTH = 100
TOP_LEFT_SQUARE_COORDS = [0, 0, SQUARE_LENGTH, SQUARE_LENGTH]
TOP_RIGHT_SQUARE_COORDS = [WINDOW_WIDTH - SQUARE_LENGTH, 0, SQUARE_LENGTH, SQUARE_LENGTH]
BOTTOM_LEFT_SQUARE_COORDS = [0, WINDOW_HEIGHT - SQUARE_LENGTH, SQUARE_LENGTH, SQUARE_LENGTH]
BOTTOM_RIGHT_SQUARE_COORDS = [WINDOW_WIDTH - SQUARE_LENGTH, WINDOW_HEIGHT - SQUARE_LENGTH, SQUARE_LENGTH, SQUARE_LENGTH]
ALL_SQUARES = [TOP_LEFT_SQUARE_COORDS, TOP_RIGHT_SQUARE_COORDS,
               BOTTOM_LEFT_SQUARE_COORDS, BOTTOM_RIGHT_SQUARE_COORDS]

# Game
POINTS_TO_WIN = 5
